version: 2

project_name: chaos-proxy-go
builds:
  - main: ./main.go
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - "-X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
changelog:
  disable: true
release:
  github:
    owner: fetch-kit
    name: chaos-proxy-go

